baseURL = "/"
languageCode = "en-us"
theme = "hugo-winston-theme-custom"
themesDir = "themes"
title = "Katie Linero"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = ""
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = true
  highlightColor = "#BADA55"
  baseColor = "#FFFFFF"
  baseOffsetColor = "#EAEAEA"
  headingColor = "#1C1B1D"
  textColor = "#4E5157"
  dotColor = "#BADA55"
  enableGoogleFonts = true
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Fira+Code:wght@400;700&family=Yeseva+One:wght@400;700&display=swap"
  fontFamilyHeading = "Yeseva One"
  fontFamilyParagraph = "Inter"
  fontFamilyMonospace = "Fira Code"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Me"
    identifier = "me"
    weight = 2
    url = "/me/"
  [[menu.main]]
    name = "Work"
    identifier = "work"
    weight = 3
    url = "/work/"
  [[menu.main]]
    name = "&c"
    identifier = "etc"
    weight = 4
    url = "/etc/"
